### ISSUE TITLE
Hierarchy browse pages should reflect theme settings

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-modules/Hierarchy#5]
As mentioned in https://github.com/omeka-s-themes/lively/issues/8, the browse pages could be more visually in line with the rest of the chosen theme. 

I noticed that the pages don't, for example, reflect the list/grid setting when available, and the toggle between list and grid view doesn't appear. 

I'm hoping the module can just be simplified to display the same way other browse pages are, rather than need theme changes to include new settings for the browse pages? I recognize it's a narrower zone with a left sidebar, but could it be otherwise the same?

I can set up some pages for comparison if you need them. For example, Lively on a site set to "toggle (default grid)" looks like this on the items browse page:
http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-second-site/item
And this on a hierarchy browse page: http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-second-site/hierarchy/5

Foundation:
https://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-fourth-site/item
https://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-fourth-site/hierarchy/1

Foundation pulls the medium derivatives for browse, while the module pulls the square.

**Comment by matthewjmckinley** [comment]
I talked this over a bit with @kimisgold and this speaks to a more general problem of modules wanting to provide a version of the browse views, without having to recreate them wholesale. It also gets more complicated because themes can have disparate settings. 

For example, list/grid toggle is available in foundation, centerrow and daily but not in the other themes, so while I got toggle working by copying and pasting the code and JS asset into the Hierarchy module, the look and behavior of the browse screen breaks when you switch to another theme that doesn't have the list/grid toggle feature implemented.

So features like this are a good conversation for future development, perhaps a view helper or something that streamlines and/or negotiates views across themes, but I'm closing this issue because I can't implement it consistently across all themes.
